### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by DongJianzhi0223** [HashDataInc/bireme#20]
您好：

  我在使用BIREME从MYSQL导数据到GP数据库的时候，在执行
DELETE FROM public.bireme_test WHERE EXISTS (SELECT 1 FROM public_bireme_test,bireme_test WHERE public.bireme_test.id=public_bireme_test.id)
 从临时表来删除数据的时候，该SQL一直卡在GP数据库无法执行，我只能把源码改成
 DELETE FROM " + table + " WHERE id in (" + sbt.substring(0,sbt.length()-1) + ");";
直接从批量的数据中获取主键的值，直接删除。

问题1：
  可否帮忙定位一下第一个DELETE语句卡住的原因。
问题2：
 请问这两种方式的在性能上有区别吗？

**Comment by zhouyuze** [comment]
https://github.com/HashDataInc/bireme/blob/d7849334c4673da86965616a4bdd78d36df1dd30/src/main/java/cn/hashdata/bireme/ChangeLoader.java#L396-L397

I think the SQL statement should be 
DELETE FROM public.bireme_test WHERE EXISTS (SELECT 1 FROM public_bireme_test WHERE public.bireme_test.id=public_bireme_test.id);
Is it a type mistake?

DELETE FROM " + table + " WHERE id in (" + sbt.substring(0,sbt.length()-1) + ");";
what do you mean by "sbt" ?
Besides, id is not always the primary key.

**Comment by wangzw** [comment]
@DongJianzhi0223 How long does the query hang? Would you please show the result of ```select * from pg_stat_activity```. Delete may be blocked by other operation.

Two queries have no performance differences .... if the planer is smart enough. But you must pay attention to compound primary key.

**Comment by wangzw** [comment]
If delete operation executed more than 10 seconds. Delete query plan will be output into log. So also check your log for more information.

https://github.com/HashDataInc/bireme/blob/d7849334c4673da86965616a4bdd78d36df1dd30/src/main/java/cn/hashdata/bireme/ChangeLoader.java#L303

**Comment by DongJianzhi0223** [comment]
各位好：

 好像是数据库的问题，我是用的是GP5.0的版本，数据库建好后，查询表格都没有问题，但是在执行JOIN等操作，或者查看表分布的语句时，也会出现HANG的现象，我们使用的主机是腾讯云，是否可以帮忙分析一下原因，我觉得HANG的问题导致执行delete操作不成功的原因。

**Comment by wangzw** [comment]
Maybe you can check the UDP connectivity of cluster. Or switch ```gp_interconnect_type``` from ```icudp``` to ```tcp```.

BTW: Greenplum community and mail list is a better place for this kind of issue.

**Comment by DongJianzhi0223** [comment]
您好：


之前安装的4.3.9的时候没有遇到这类的问题
我从5.0版本换回4.3在COPY数据的时候为什么一次COPY命令会出现三个用户来执行，而且都HANG在这里。
请问能协助帮忙定位一下问题吗？


十分感谢！！ 









原始邮件
发件人:Zhanwei Wangnotifications@github.com
收件人:HashDataInc/biremebireme@noreply.github.com
抄送:DongJianzhi02231197009127@qq.com; Mentionmention@noreply.github.com
发送时间:2017年10月18日(周三) 17:09
主题:Re: [HashDataInc/bireme] 提问 (#20)


Maybe you can check the UDP connectivity of cluster. Or switch gp_interconnect_type from icudp to tcp.
BTW: Greenplum community and mail list is a better place for this kind of issue.
