### ISSUE TITLE
使用maxwell时,"commit":true  这个字段在bireme里面有用到吗？

### ISSUE THREAD

**Issue by jinxiaoxin** [HashDataInc/bireme#24]
![image](https://user-images.githubusercontent.com/26498890/33202581-04b3a82a-d138-11e7-82ae-7b58f490e45d.png)
commit和xid在bireme里面用在何处？

**Comment by zhouyuze** [comment]
Since Bireme does not support transaction, this field is not used.

**Comment by jinxiaoxin** [comment]
@zhouyuze   thx
那xid呢？

**Comment by zhouyuze** [comment]
The "xid" is not used either.

**Comment by jinxiaoxin** [comment]
@zhouyuze ok，thx

**Comment by jinxiaoxin** [comment]
@zhouyuze    ts这个字段用到了吗？用到的话  具体意思是 当前系统时间吗？

**Comment by wangzw** [comment]
`ts` is the timestamp when the tuple was produced into kafka
