### ISSUE TITLE
我想在bireme入口时,更改json的格式。

### ISSUE THREAD

**Issue by jinxiaoxin** [HashDataInc/bireme#26]
由于我使用OGG to kafka，数据格式和bireme所接收格式不太符合
所以想在kafka接收后 更改其数据格式
想在获取到record时  更改下  数据结构，我模拟用maxwell的格式，
我只更改了MaxwellProvider.java
在解析数据之前，先更改下数据格式，但是我更改编译完，运行启动，却发现他不会copy数据到GP中，
不知道哪里还需要更改？
我用的版本是bireme-1.0.0

代码如下
`public class MaxwellChangeTransformer extends KafkaTransformer {
    public class MaxwellRecord implements Record {
      public String dataSource;
      public String database;
      public String table;
      public Long produceTime;
      public RowType type;
      public JsonObject data;
      public JsonObject old;

      public MaxwellRecord(String changeValue) {
        JsonParser jsonParser = new JsonParser();
        JsonObject value = (JsonObject) jsonParser.parse(changeValue);
        
        //先转换为bireme所需格式
		value=changeJsonForOracle(jsonParser, value);

        
        this.dataSource = getProviderName();
        this.database = value.get("database").getAsString();
        this.table = value.get("table").getAsString();
        this.produceTime = value.get("ts").getAsLong();
        this.data = value.get("data").getAsJsonObject();

        if (value.has("old") && !value.get("old").isJsonNull()) {
          this.old = value.get("old").getAsJsonObject();
        }

        switch (value.get("type").getAsString()) {
          case "insert":
            type = RowType.INSERT;
            break;

          case "update":
            type = RowType.UPDATE;
            break;

          case "delete":
            type = RowType.DELETE;
            break;
        }
      }

    /**
     * 增加转换oracle日志为bireme所需日志方法
     * @param jsonParser
     * @param value
     */
	private JsonObject changeJsonForOracle(JsonParser jsonParser, JsonObject value) {
		// 解析出database名称并存入json中
		value.addProperty("database",
				value.get("table").getAsString().split("\\.")[0]);
		// 解析出table名称并存入json中
		value.addProperty("table", value.get("table").getAsString()
				.split("\\.")[1]);
		// 解析出type并存入json中
		String typeStr = "";
		switch (value.get("op_type").getAsString()) {
		case "I":
			typeStr = "insert";
			break;

		case "U":
			typeStr = "update";
			break;

		case "D":
			typeStr = "delete";
			break;
		}
		value.addProperty("type", typeStr);
		// 删除op_type字段
		value.remove("op_type");
		//如果是update操作,则解析after和before
		if (typeStr.equals("update")) {
			JsonObject valueBefore = (JsonObject) jsonParser.parse(value.get(
					"before").toString());
			JsonObject valueAfter = (JsonObject) jsonParser.parse(value.get(
					"after").toString());
			JsonObject old = new JsonObject();
			for (Map.Entry<String, JsonElement> entry : valueBefore.entrySet()) {
				if (!valueBefore.get(entry.getKey()).equals(
						valueAfter.get(entry.getKey()))) {
					old.add(entry.getKey(), valueBefore.get(entry.getKey()));
				}
			}
			value.add("old", old);
			value.remove("before");
			value.add("data", valueAfter);
			value.remove("after");
		}else{
			//如果不是update,则只把after字段换成data字段
			value.add("data", value.get("after"));
			value.remove("after");
		}
		//转换ts为long值
		SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
        Date date=null;
		try {
			date = (Date) sdf.parse(value.get("current_ts").getAsString());
		} catch (ParseException e) {
			e.printStackTrace();
		}
        value.addProperty("ts", date.getTime()/1000);
        value.remove("current_ts");
        return value;
	}
`

**Comment by wangzw** [comment]
Convert OGG format to Maxwell is not an ideal solution. We should support OGG native format. Adding a new OGG Pipeline for v2.0 is the right way.

@jinxiaoxin Would you like to contribute a OGG pipeline?

**Comment by jinxiaoxin** [comment]
如果有时间的话，当然愿意编写此部分代码。
但是我现在需要稍微改一下json格式来使用（现在正急用），
想问下，获取record并解析出来 是只在MaxwellRecord这个class中吗？
还是说有其他的地方？
@wangzw

**Comment by wangzw** [comment]
Yes, json string is only parsed in the constructor of MaxwellRecord.

**Comment by jinxiaoxin** [comment]
那其实我要是改JSON格式  在这里面改就足够了？
不用去改其他地方了吧？

**Comment by wangzw** [comment]
Maybe you also need to take care how to convert columns into CSV format in the transformer.
