### ISSUE TITLE
Bireme启动正常，maxwell的Mysql 同步至Greenplum，在mysql中插入数据greenplum中没有反应。。。 

### ISSUE THREAD

**Issue by SbloodyS** [HashDataInc/bireme#32]
12:56:50 INFO  Bireme - Start getting metadata of target tables from target database.
12:56:50 INFO  Bireme - Finish getting metadata of target tables from target database.
12:56:50 INFO  Bireme - Start establishing connections for loaders.
12:56:50 INFO  Bireme - Finishing establishing 1 connections for loaders.
12:56:50 INFO  ChangeLoader - Loader Start, corresponding table stg.test.
12:56:50 INFO  TaskGenerator - TaskGenerator Start.
12:56:50 INFO  Dispatcher - Dispatcher Start.
12:56:50 INFO  Provider mysql - Provider mysql Start.

请问哪里出问题了呢？

**Comment by wangzw** [comment]
Please verify the content in kafka and check if bireme poll data from correct kafka topic.

**Comment by SbloodyS** [comment]
emmm....It seems like maxwell was not working well...Thanks~
