### ISSUE TITLE
Bireme daemon exits with NullPointerException

### ISSUE THREAD

**Issue by aStonegod** [HashDataInc/bireme#4]
10:51:45 FATAL Dispatcher - Dispatcher exit on error: java.lang.NullPointerException
10:51:45 INFO  Bireme - stop Bireme daemon
10:51:45 INFO  Bireme - set stop flag to true
10:51:45 INFO  ChangeLoader - Loader exit, corresponding table public.tbpaymentorder.
10:51:45 INFO  Bireme - Bireme exit
10:51:45 ERROR Provider maxwell1 - Provider maxwell1 exit on error. Message null
10:51:45 INFO  Bireme - destroy Bireme daemon

table映射：
testpayment.tbpaymentorder= public.tbpaymentorder

**Comment by wangzw** [comment]
Would you please post more details of you configuration?

**Comment by aStonegod** [comment]
# target database where the data will sync into.
target.url = jdbc:postgresql://gpmaster:1921/gpcluster
target.user = gpadmin
target.passwd = gpadmin

# data source name list, separated by comma.
data_source = maxwell1

# data source "mysql1" type
maxwell1.type = maxwell
# kafka server which maxwell write binlog into.
maxwell1.kafka.server = middle:9092
# kafka topic which maxwell write binlog into.
maxwell1.kafka.topic = testpay

# application performance monitor report type: "none", "console", "jmx"
metrics.reporter=console
# interval of console APM reporter.
metrics.reporter.console.interval = 10

# JDBC connection pool size of target database.
loader.conn_pool.size = 10
# queue size of task for each table which is waiting for load.
loader.task_queue.size = 2

# number of threads used to transform data source record into target format.
transform.thread_pool.size = 10

# number of threads used to generate load tasks.
merge.thread_pool.size = 10
# interval of generating a load task in milliseconds.
merge.interval = 10000
# max tuple size for a load task
merge.batch.size = 50000

**Comment by zhouyuze** [comment]
Would please post some examples of Kafka consume record?

**Comment by aStonegod** [comment]
HI, kafka record like this :
{"database":"testpayment","table":"tbpaymentorder","type":"insert","ts":1505879683,"xid":9753352,"commit":true,"position":"mysql-bin-m.000014:626525214","data":{"PM_SEQ_NO":"20170920FT018880133","BIZ_PM_SEQ_NO":"2017092004018920133","RELATE_PM_SEQ_NO":null,"PM_TYPE":"FT","GMT_PM":"2017-09-20 03:55:44","GMT_MODIFIED":"2017-09-20 03:54:43","GMT_CREATE":"2017-09-20 03:54:43","MEMO":"2017092011552570735005004","PAY_CHANNEL":"01","BIZ_PRODUCT_CODE":"20201"}}

**Comment by zhouyuze** [comment]
@aStonegod Currently, the column name of table must be the same in MySQL and GPDB.
