### ISSUE TITLE
Bireme 同步失败

### ISSUE THREAD

**Issue by SbloodyS** [HashDataInc/bireme#45]
Bireme如果和maxwell一起启动的时候，数据可以正常同步，但是在正常同步后Bireme restart后同步就停止了。。。BIreme的启动日志是正常的。。。请问可以如何解决呢~

**Comment by wangzw** [comment]
When you restart Bireme, it will continue the work where it was stopped. So maybe it is not stopped but no data to sync anymore in kafka.

Otherwise you may follow the steps in issue #47 to check what happened.

**Comment by wangzw** [comment]
duplicate with #47

**Comment by jinxiaoxin** [comment]
@SbloodyS 你好，我想请教下，bireme在表数量增加之后，数据无法同步的问题，可以留下联系方式，交流一下吗

**Comment by SbloodyS** [comment]
@jinxiaoxin 我已经没有在用Bireme了。。。

**Comment by jinxiaoxin** [comment]
@SbloodyS 那现在用的是dbsync吗？它的同步效率如何？我qq：305432835  能加下交流下吗~

**Comment by SbloodyS** [comment]
@jinxiaoxin 460888207 加我吧~

**Comment by yxs1112003** [comment]
使用什么工具能说一下吗？ @SbloodyS @jinxiaoxin
