### ISSUE TITLE
consider using subscribe() instead of assign()

### ISSUE THREAD

**Issue by wangzw** [HashDataInc/bireme#53]
https://github.com/HashDataInc/bireme/blob/8f51d4fd7217ee72a728f15ac666f5110d11254f/src/main/java/cn/hashdata/bireme/pipeline/MaxwellPipeLine.java#L31

Even for Maxwell, we are using the same consumer group so that it is better to use subscribe() instead of assign()

Kafka would not let two consumers in the same consumer group to read from the same partition. So it would be safe to make such change.

**Comment by zhouyuze** [comment]
@wangzw subscribe() method subscribe to dynamically assigned partitions. For maxwell, we build a pipeline for each partition, so I think using assign() to explicitly subscribe to a fixed partitions is a better chose.

**Comment by wangzw** [comment]
@zhouyuze That's correct that we should build a pipeline for each partition,  but by subscribe the topic for each partition and leave the kafka to dynamically assign partitions instead of do it manually.

**Comment by zhouyuze** [comment]
@wangzw I don't know exactly how "dynamically" works. Suppose we have two partition for topic A, and I create a consumer to subscribe A. Will it dynamically be assigned to both partition 1 and partition 2 ? But if then I create another consumer to subscribe A, will the partition 2 dynamically be assigned to the last consumer ? So both consumers have subscribed to partition 2. I can't guarantee the order  in partition 2. I think if we want to use subscribe, we must make it clear how "dynamically" work.

**Comment by zhouyuze** [comment]
@wangzw @Rucfisher There is another problem. When the latter consumer failed, will partition 2 dynamically be assigned to the first consumer? If so, we must make sure that it will consume from the last committed offset not from where the latter consumer failed. Some experiment must be designed to verify correctness or read the source of kafka consumer.

**Comment by wangzw** [comment]
If two consume in the same consume group and subscribe to the same topic which has two partitions, each consume will only works on one partition. Kafka will not let two consume in the same consume group read from same partition. So we can guarantee the order.

**Comment by wangzw** [comment]
@zhouyuze Good point about the failure. kafka will rebalance the consumer on failure, but only uncommitted message will be delivered to consumer. So it is safe too.

**Comment by zhouyuze** [comment]
@wangzw I understand. We can guarantee that we start all consumer simultaneously. It works currently. But if one consumer failed, we can't restart it while bireme is running. (Also currently bireme doesn't support this operation.) Suppose that bireme support this problem, there will be another problem. Consumer 1 subscribe partition 1 and consumer 2 subscribe partition 2. Suddenly, consumer 2 failed, and consumer 1 subscribe both partition 1 and partition 2.  Consumer 1 poll record A but not commit it. Then we restart consumer 2 while bireme is running. Kafka will rebalance the consumer and assign partition 2 to consumer 2. Later, Consumer 2 poll record A and and record B from kafka. So now we can't guarantee consumer 1 commit record A before Consumer 2 commit record B.

**Comment by zhouyuze** [comment]
I understand.
