### ISSUE TITLE
when one pipeline doesn't work, bireme stop

### ISSUE THREAD

**Issue by Rucfisher** [HashDataInc/bireme#68]
when an error occurred in one pipeline, it seems that all pipeline do not work.

**Comment by wangzw** [comment]
https://github.com/HashDataInc/bireme/blob/8e140644be1e634bef4738e9f133537432d23fd6/src/main/java/cn/hashdata/bireme/ChangeLoader.java#L122

We do not release connection when error happen.
We needs reconsider the logic of creating/releasing connection.

**Comment by wangzw** [comment]
This is the design at this time, but may be changed later.
