### ISSUE TITLE
maxwell和bireme处理时间问题

### ISSUE THREAD

**Issue by shubifeng** [HashDataInc/bireme#92]
当库表较多和kafka消息队列中 消息数 过于庞大时,  当maxwell.properties配置同步一个表时, bireme入库时间会很长.

**Comment by wangzw** [comment]
Please update your benchmark result and more details.

Usually it is because that the database cannot handle the deleting/loading quickly. Extend you database cluster and test again.

**Comment by shubifeng** [comment]
应该不是数据库集群问题.

所有的binlog解析到maxwell-topic,   要么是kafka队列读的慢,  因为有一部分数据还能快速更新, 有一部分表的数据很慢很慢. 


没数据的时候也建立临时库?  为什么会没有自动删除?
