### ISSUE TITLE
数据插入排重有问题

### ISSUE THREAD

**Issue by shubifeng** [HashDataInc/bireme#95]
执行过程中终止,在执行bireme. 

数据库会报`duplicate key value violates unique constraint "external_order_result_log_pkey"`

**Comment by wangzw** [comment]
Is is very important to handle overlapped Binlog for failure recovery. But in another hand, it should be introduce cost as less as possible.

So Bireme will only work in two modes which are optimistic and pessimistic mode.

Optimistic mode: Assume no overlap of Binlog and no conflict with database. Bireme directly bulk load data into database.

Pessimistic mode: Assume overlap and conflict exists, delete first and then load data into database.

Bireme will entry pessimistic mode if duplicate key found during the insert, that is why you can find such error message from database running log.

Bireme will leave pessimistic mode if it delete nothing before insert.
