### ISSUE TITLE
重写了TABLE类里面校验表及主键的逻辑，提高初始化的速度

### ISSUE THREAD

**Issue by DongJianzhi0223** [HashDataInc/bireme#98]
目前生产数据里表比较大，每天的增删改操作比较多，当需要同步的表过多，或者系统表逐渐膨胀的时候，dbMetaData = conn.getMetaData();
rs = dbMetaData.getTables();
rs = dbMetaData.getPrimaryKeys();
几个方法光校验表和主键就要花费10多分钟的时间，会影响数据同步的效率。

查询了POSTGRESQL里JDBC中getTables()和getPrimaryKeys()的原理，通过批量查询校验表及主键，从原有的初始化12分钟缩短到12秒，提供代码参考。

Bireme 类getTableInfo()方法的代码段：
protected void getTableInfo() throws BiremeException {
        logger.info("Start getting metadata of target tables from target database.");
        Map<String, JSONObject> tableInfoMap = null;
        tableMap = cxt.tableMap;
        String[] strArray;
        Connection conn = BiremeUtility.jdbcConn(cxt.conf.target);
        try {
            tableInfoMap = GetPrimaryKeys.getPrimaryKeys(cxt.tableMap, conn);
        } catch (Exception e) {
            String message = "董鉴之写的方法有问题！";
            throw new BiremeException(message, e);
        }

        for (String fullname : cxt.tableMap.values()) {
            if (cxt.tablesInfo.containsKey(fullname)) {
                continue;
            }
            strArray = fullname.split("\\.");
            cxt.tablesInfo.put(fullname, new Table(strArray[1], tableInfoMap, conn));
        }

        try {
            conn.close();
        } catch (SQLException ignore) {
        }

        logger.info("Finish getting metadata of target tables from target database.");
    }

TABLE类重写的代码段：
/**
     * Get metadata of a specific table using a given connection and construct a new {@code Table}.
     *
     * @param tableMap  Table name Map
     * @param conn      Connection to the database
     * @throws BiremeException - Wrap and throw Exception which cannot be handled.
     */
    public Table(String tableName, Map<String, JSONObject> tableMap, Connection conn) throws BiremeException {
        this.ncolumns = 0;
        this.columnName = new ArrayList<String>();
        this.columnType = new ArrayList<Integer>();
        this.columnPrecision = new ArrayList<Integer>();
        this.columnScale = new ArrayList<Integer>();
        this.keyNames = new ArrayList<String>();
        this.keyIndexs = new ArrayList<Integer>();

        Statement statement = null;
        ResultSet rs = null;
        ResultSetMetaData rsMetaData = null;

        try {
            this.keyIndexs.add(tableMap.get(tableName).getInteger("keyindexs"));
            this.keyNames.add(tableMap.get(tableName).getString("column_name"));

            statement = conn.createStatement();

            String queryTableInfo = "select * from public." + tableName + " where 1=2";
            rs = statement.executeQuery(queryTableInfo);
            rsMetaData = rs.getMetaData();
            this.ncolumns = rsMetaData.getColumnCount();

            for (int i = 0, len = rsMetaData.getColumnCount(); i < len; i++) {
                this.columnName.add(rsMetaData.getColumnName(i + 1));
                this.columnType.add(rsMetaData.getColumnType(i + 1));
                this.columnPrecision.add(rsMetaData.getPrecision(i + 1));
                this.columnScale.add(rsMetaData.getScale(i + 1));
            }
        } catch (SQLException e) {
            try {
                conn.close();
            } catch (SQLException ignore) {
            }
            String message = "Could not get metadata for public." + tableName + ".\n";
            throw new BiremeException(message, e);
        }
    }

自己写的校验表和主键的类：
public class GetPrimaryKeys {
    private static Logger logger = LogManager.getLogger("Bireme." + GetPrimaryKeys.class);

    public static Map<String, JSONObject> getPrimaryKeys(HashMap<String, String> tableMap, Connection conn) throws Exception {
        Statement statement = null;
        ResultSet resultSet = null;
        ResultSet tableRs = null;
        Map<String, JSONObject> table_map = new HashMap<>();
        List<String> checkTableMap = new ArrayList<>();
        String[] strArray;
        StringBuilder sb = new StringBuilder();
        sb.append("(");
        for (String fullname : tableMap.values()) {
            strArray = fullname.split("\\.");
            sb.append("'").append(strArray[1]).append("',");
        }
        String tableList = sb.toString().substring(0, sb.toString().length() - 1) + ")";
        String tableSql = "select tablename from pg_tables where schemaname='public' and tablename in " + tableList + "";
        String prSql = "SELECT NULL AS TABLE_CAT, " +
                "n.nspname  AS TABLE_SCHEM, " +
                "ct.relname AS TABLE_NAME, " +
                "a.attname  AS COLUMN_NAME, " +
                "(i.keys).n AS KEY_SEQ, " +
                "ci.relname AS PK_NAME " +
                "FROM pg_catalog.pg_class ct JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid) " +
                "JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid) " +
                "JOIN ( SELECT i.indexrelid, i.indrelid, i.indisprimary, information_schema._pg_expandarray(i.indkey) AS KEYS FROM pg_catalog.pg_index i) i ON (a.attnum = (i.keys).x AND a.attrelid = i.indrelid) " +
                "JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) WHERE TRUE AND n.nspname = 'public' AND ct.relname in " + tableList + " AND i.indisprimary ORDER BY TABLE_NAME, pk_name, key_seq";
        try {
            statement = conn.createStatement();
            tableRs = statement.executeQuery(tableSql);

            while (tableRs.next()) {
                checkTableMap.add(tableRs.getString("tablename"));
            }

            resultSet = statement.executeQuery(prSql);
            while (resultSet.next()) {
                JSONObject jsonObject = new JSONObject();
                jsonObject.put("keyindexs", resultSet.getInt("KEY_SEQ") - 1);
                jsonObject.put("column_name", resultSet.getString("COLUMN_NAME"));
                table_map.put(resultSet.getString("TABLE_NAME"), jsonObject);
            }

            if (table_map.size() != tableMap.size()) {
                String message = "GP的表和MYSQL的表对不上！";
                throw new BiremeException(message);
            } else {
                logger.info("MYSQL、GREENPLUM同步对应表校验完毕，状态正常！");
            }

            if (table_map.size() != tableMap.size()) {
                String message = "有表没主键！";
                throw new BiremeException(message);
            } else {
                logger.info("GREENPLUM表主键校验完毕，状态正常！");
            }

        } catch (SQLException e) {
            try {
                statement.close();
                conn.close();
            } catch (SQLException ignore) {
            }
            String message = "Could not get PrimaryKeys";
            throw new BiremeException(message, e);
        }

        return table_map;
    }
}

**Comment by wangzw** [comment]
Would you please file a pull request?

**Comment by DongJianzhi0223** [comment]
把代码打包发送了

**Comment by DongJianzhi0223** [comment]
只是临时修改，满足性能需求，里面还有几个地方需要优化一下，仅供参考。

**Comment by wangzw** [comment]
Thanks for your contribution. But the pull request #99 has only irrelevant previous commits and none of them is your commit.

Here are some good links about creating pull request. 

https://help.github.com/articles/about-pull-requests/
https://help.github.com/articles/creating-a-pull-request/

and this link is in Chinese:
https://www.zhihu.com/question/21682976

**Comment by wangzw** [comment]
I saw the zip file uploaded and @Rucfisher will create a new pull request based on it.
